# Generated by Django 5.1.1 on 2024-09-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_spamreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
