# Generated by Django 5.1.1 on 2024-09-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_spamreport_reported_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spamreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spamreport',
            name='reported_by',
        ),
    ]
